# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# change this line if you do not want to import all submodules:
axolotlclient.modules.all=true

# Mod Properties
version=3.1.9-beta.1
maven_group=io.github.axolotlclient
archives_base_name=AxolotlClient

# Shared Dependencies
fabric_loader=0.18.4
config=3.1.12
